In [1]:
import numpy as np

In [2]:
vet = np.array([1, 2, 3, 6, 8, 9, 10, 11, 13, 14, 15, 101, 15, 10, 13, 12, 3, 1, 102])
vet

array([  1,   2,   3,   6,   8,   9,  10,  11,  13,  14,  15, 101,  15,
        10,  13,  12,   3,   1, 102])

In [3]:
type(vet) #verificar o tipo

numpy.ndarray

In [5]:
vet2 = np.array([1, 2, 3, 4, 5])
vet2.cumsum() #soma dos anteriores com o próximo (espécie de fibonacci)

array([ 1,  3,  6, 10, 15])

In [6]:
vet[4] #printando o valor da lista com o tipo

np.int64(8)

In [7]:
print(vet[4]) #printando o valor da lista sem dizer o tipo

8


In [9]:
vet[0] = -1 #alterando o valor do primeiro índice da lista
vet

array([ -1,   2,   3,   6,   8,   9,  10,  11,  13,  14,  15, 101,  15,
        10,  13,  12,   3,   1, 102])

In [14]:
vet = np.append(vet,105) #acrescentar o número na última posição
vet

array([ -1,   2,   3,   6,   8,   9,  10,  11,  13,  14,  15, 101,  15,
        10,  13,  12,   3,   1, 102, 105])

In [16]:
vet = vet[:-1] #eu quero todos os numeros da lista, exceto o último
vet

array([ -1,   2,   3,   6,   8,   9,  10,  11,  13,  14,  15, 101,  15,
        10,  13,  12,   3,   1, 102])

In [17]:
vet = np.delete(vet,-3) #deletando a terceira posição de trás pra frente
vet

array([ -1,   2,   3,   6,   8,   9,  10,  11,  13,  14,  15, 101,  15,
        10,  13,  12,   1, 102])

In [18]:
vet.shape #diz a qtd de elementos que tem dentro da lista

(18,)

In [19]:
vetor = np.array ([[0, -5], [11, 300]]) #criando matriz (lista de lista)
vetor

array([[  0,  -5],
       [ 11, 300]])

In [20]:
vetor.shape

(2, 2)

In [21]:
vetor3x2 = np.array ([[1, 2], [3, 4], [5, 6]])
vetor3x2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
vetor3x2.shape

(3, 2)

In [23]:
vetor2x3 = np.array ([[1, 2, 3], [4, 5, 6]])
vetor2x3

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
vetor2x3.shape

(2, 3)

In [27]:
y = np.arange(2, 200, 4) #o próprio numpy cria a matriz, mas vc define: qual o primeiro nº, qual o último nº e de quanto em quanto será acrescentado
y

array([  2,   6,  10,  14,  18,  22,  26,  30,  34,  38,  42,  46,  50,
        54,  58,  62,  66,  70,  74,  78,  82,  86,  90,  94,  98, 102,
       106, 110, 114, 118, 122, 126, 130, 134, 138, 142, 146, 150, 154,
       158, 162, 166, 170, 174, 178, 182, 186, 190, 194, 198])

In [28]:
#unique: remove repetições
unicos_vet = np.unique(vet)
unicos_vet

array([ -1,   1,   2,   3,   6,   8,   9,  10,  11,  12,  13,  14,  15,
       101, 102])

In [33]:
idades = np.array ([44, 45, 23, 23, 28, 19, 20, 19, 17, 51, 29 , 28, 31, 32])
mediaIA2.mean() #já dá a média

np.float64(29.214285714285715)

In [34]:
x = round(idades.mean(),2) #arredondando a média para duas casas decimais
x

np.float64(29.21)

In [36]:
j = np.unique(idades) #removendo as repetições das idades
j

array([17, 19, 20, 23, 28, 29, 31, 32, 44, 45, 51])

In [38]:
j.mean()

np.float64(30.818181818181817)

In [40]:
j = round(idades.mean(),2)
j

np.float64(29.21)